### PR TITLE
Restructured with config file and updated readme.

### PR DESCRIPTION
**Pull request by Dsujan**

### CODE REVIEW

**Comment by Dsujan** [comment]
Check the PR.

**Comment by Robert0306** [comment]
Hi, 

Thank you for your work. 
Im quite new to flask, but i guess i also should setup config to get info from environment Variables.
What is your take on this?

**Comment by Dsujan** [comment]
@Robert0306  Yes absolutely you setup config to get info from environment variables.  Variables like password, username, secret tokens should be set to environment variables and loaded from there in config. Doing this would hide your confidential credentials from anyone who reads your source code.

**Comment by Robert0306** [comment]
@Dsujan I tought so, will update this to day. Thanks!

**Pull request merged**
